keys = [
    'oi12u809a548gbux',
    '21i3ouain091jamp',
    '9213087210hasda1'
]

encrypting_upper_alphabet = {
    'A': '/Gk,',
    'B': ':.k9',
    'C': '19kç',
    'D': '[})a',
    'E': 'Mba)',
    'F': '/*+l',
    'G': '$3%k',
    'H': '0k1]',
    'I': '36j*',
    'J': 'aZjm',
    'K': 'A@!Ç',
    'L': '#gb0',
    'M': 'ç.HG',
    'N': '84a1',
    'O': '6fA!',
    'P': 'O0lm',
    'Q': '=[.X',
    'R': '58jh',
    'S': '*byc',
    'T': '#kOp',
    'U': 'ÇxZ7',
    'V': 'odKS',
    'W': '0pç,',
    'X': '.;@*',
    'Y': '+=_h',
    'Z': '8Asc',
    'Ç': '7*0a'
}

encrypting_numbers = {
    '0': '=+8b',
    '1': 'Vc8H',
    '2': 'Eo%$',
    '3': '/;.T',
    '4': '*8q>',
    '5': '<{]1',
    '6': '7hj,',
    '7': '09km',
    '8': '8jm&',
    '9': '+.0z',
    ' ': '10m,',
    ',': '21Ja',
    '.': '9*m)',
    ':': '1%4v',
    '?': '9!@6',
    '!': '19ol',
}

encrypting_lower_alphabet = {
    'a': 'O81.',
    'b': ']kP2',
    'c': '!$/k',
    'd': '9*-n',
    'e': '@Mbç',
    'f': 'od#P',
    'g': '7Az|',
    'h': 'q^~u',
    'i': 'çl.,',
    'j': ';?kq',
    'k': '81*+',
    'l': ')pmd',
    'm': '7Dm@',
    'n': '09k,',
    'o': 'ç.;!',
    'p': 'uI8&',
    'q': 'Qe%7',
    'r': '0j,+',
    's': ']{m:',
    't': 'Jxz=',
    'u': '/3m,',
    'v': '1.?0',
    'w': '0,fe',
    'x': 'PqEo',
    'y': '0-_=',
    'z': 'pçW3',
    'ç': '1*#4',
}

what_to_do = {
    1: 'Criptografar um arquivo',
    2: 'Descriptografar um arquivo',
    3: 'Criptografar um texto',
    4: 'Descriptografar um texto'
}

encrypting_one_bit = {
    'A': '&F?2dtfZ87+!^J2+',
    'B': '5#kWw#U!9UtNU3sa',
    'C': 'FhH6DHr&a!WXyEDn',
    'D': 'zm95+^fXegXHg4gH',
    'E': 'yd^75hHWL^5K@kx#',
    'F': 'cdFNMW%WkM5n+JR#',
    'G': '2?uLFs??B3Ec4gkp',
    'H': '6*F!GK8xk5U*VFXm',
    'I': 'atZ5?-$UyHKJsx9$',
    'J': 'M^3!P^m8Yu?eb?RH',
    'K': 'Ve+?Q6xqAuS62+BD',
    'L': 'eFr8=DykYa@tT!9j',
    'M': 'ZAPap$6wc7Z%YWBe',
    'N': 'euc7dZ5L+*Mu6u8p',
    'O': 'WEp^!#4tP&=jK&7B',
    'P': 'VUvPj_dCEnShe847',
    'Q': '5!%zgvs8M5?*buRd',
    'R': 'H@fRw3#H$r@n&m=t',
    'S': 'Udx)u853P^z@Zg$c',
    'T': '$XH-Mfbpx85+7+Q$',
    'U': 'A#5uJSKfxtk@R^R&',
    'V': 'fJc42FuyP*R!87_A',
    'W': 'YX3FM_&8mt45?u8#',
    'X': 'bm=@TYz5$qhR=GB8',
    'Y': 'DN@aGs8B7rDTCPpF',
    'Z': '@xJZx9?4eBeKYZ^U',
    'Ç': 'H7D$KsJtzv+2YjF$',
    '0': '_w@s+2D9Fn_-n287',
    '1': 'd58b-yxEVzx2eV_K',
    '2': '_DwP5-Q9bGwxeT@=',
    '3': '5xN5fX#KG&UcaEyq',
    '4': 'bL@^?s#38ThKKf!C',
    '5': 'GYPT9Azp6Shx=sw=',
    '6': '++T5VsDvb9*!FYYh',
    '7': 'BAT3eA+RV2md?S+7',
    '8': 'EPWMkqg5FpA3^yVU',
    '9': '3Z#^4rHBWg@YU_3D',
    ' ': 'HGsWZktYrwde4=&=',
    ',': 'J*a*Rqu4vs_M2S&A',
    '.': 'UZFdy2fPG*%v97vV',
    ':': '#5@2HPTtBUMV2tJ@',
    '?': 'VZT9Fq8H?!pMxh&U',
    '!': 'Kz!PtzR9#?zDzheX',
    'a': 'kS+U&397#yE8ugz@',
    'b': '6sR6*cqMSk&_3gTd',
    'c': '&BTy=4J5dy!NMVbr',
    'd': 'qP=LvGh_=p6Lwf5r',
    'e': 'X%k=^H=!5rD_@*bD',
    'f': 'rY92hMFSXsZK+5H*',
    'g': 'j@U!*c?js#wD2yLP',
    'h': '#!qgnZE5J*gGz36x',
    'i': '=pVjNTGhq_+828_b',
    'j': 'J%M35pAE+zR#KwHn',
    'k': '9=8Vv65#rgPQs!9B',
    'l': 'UH-+4CrnhLgz_ZYC',
    'm': '4naU%qnwRqUzg2R8',
    'n': 'P9*C_3n$dAfYkNJ7',
    'o': 'RhJ@AdNmLK!Qe8-r',
    'p': 'd9fv^qB*TWM6#_Cv',
    'q': 'wwTa3VPPdgNp%?3v',
    'r': 'B!4nGNY6U6K3KMeN',
    's': 'UMhs8dchYq%Y*-Dd',
    't': 'Yp=CrMB9L=j=*j6k',
    'u': 'rYXH^jch49uks&?w',
    'v': '!GmwB8CszE#TeGHN',
    'w': 'aVrSrEJF?J6RBtch',
    'x': 'p$?!eV8j8?cGu6xt',
    'y': 'Rm$Bf9Gyu6ATY$Y6',
    'z': 'yh@+Us2MQr8H!P5k',
    'ç': 'bC8n*ndMA#saU5=p',
}

encrypting_two_bit = {
    'A': '87+!^J2+',
    'B': '9UtNU3sa',
    'C': 'a!WXyEDn',
    'D': 'egXHg4gH',
    'E': 'L^5K@kx#',
    'F': 'cdFNMW%W',
    'G': '2?uLFs??',
    'H': '6*F!GK8x',
    'I': 'atZ5?-$U',
    'J': 'M^3!P^m8',
    'K': 'Ve+?Q6xq',
    'L': 'eFr8=Dyk',
    'M': 'ZAPap$6w',
    'N': 'euc7dZ5L',
    'O': 'WEp^!#4t',
    'P': 'VUvPj_dC',
    'Q': '5!%zgvs8',
    'R': 'H@fRw3#H',
    'S': 'Udx)u853',
    'T': '$XH-Mfbp',
    'U': 'A#5uJSKf',
    'V': 'fJc42Fuy',
    'W': 'YX3FM_&8',
    'X': 'bm=@TYz5',
    'Y': 'DN@aGs8B',
    'Z': '@xJZx9?4',
    'Ç': 'H7D$KsJt',
    '0': '_w@s+2D9',
    '1': 'd58b-yxE',
    '2': '_DwP5-Q9',
    '3': '5xN5fX#K',
    '4': 'bL@^?s#3',
    '5': 'GYPT9Azp',
    '6': '++T5VsDv',
    '7': 'BAT3eA+R',
    '8': 'EPWMkqg5',
    '9': '3Z#^4rHB',
    ' ': 'HGsWZktY',
    ',': 'J*a*Rqu4',
    '.': 'UZFdy2fP',
    ':': '#5@2HPTt',
    '?': 'VZT9Fq8H',
    '!': 'Kz!PtzR9',
    'a': 'kS+U&397',
    'b': '6sR6*cqM',
    'c': '&BTy=4J5',
    'd': 'qP=LvGh_',
    'e': 'X%k=^H=!',
    'f': 'rY92hMFS',
    'g': 'j@U!*c?j',
    'h': '#!qgnZE5',
    'i': '=pVjNTGh',
    'j': 'J%M35pAE',
    'k': '9=8Vv65#',
    'l': 'UH-+4Crn',
    'm': '4naU%qnw',
    'n': 'P9*C_3n$',
    'o': 'RhJ@AdNm',
    'p': 'd9fv^qB*',
    'q': 'wwTa3VPP',
    'r': 'B!4nGNY6',
    's': 'UMhs8dch',
    't': 'Yp=CrMB9',
    'u': 'rYXH^jch',
    'v': '!GmwB8Cs',
    'w': 'aVrSrEJF',
    'x': 'p$?!eV8j',
    'y': 'Rm$Bf9Gy',
    'z': 'yh@+Us2M',
    'ç': 'bC8n*ndM',
}

encrypting_three_bit = {
    'A': '7+!J+',
    'B': 'UtN3a',
    'C': '!WXEn',
    'D': 'gXH4H',
    'E': '^5Kk#',
    'F': 'dFNWW',
    'G': '?uLs?',
    'H': '*F!Kx',
    'I': 'tZ5-U',
    'J': '^3!^8',
    'K': 'e+?6q',
    'L': 'Fr8Dk',
    'M': 'APa$w',
    'N': 'uc7ZL',
    'O': 'Ep^#t',
    'P': 'UvP_C',
    'Q': '!%zv8',
    'R': '@fR3H',
    'S': 'dx)83',
    'T': 'XH-fp',
    'U': '#5uSf',
    'V': 'Jc4Fy',
    'W': 'X3F_8',
    'X': 'm=@Y5',
    'Y': 'N@asB',
    'Z': 'xJZ94',
    'Ç': '7D$st',
    '0': 'w@s29',
    '1': '58byE',
    '2': 'DwP-9',
    '3': 'xN5XK',
    '4': 'L@^s3',
    '5': 'YPTAp',
    '6': '+T5sv',
    '7': 'AT3AR',
    '8': 'PWMq5',
    '9': 'Z#^rB',
    ' ': 'GsWk#',
    ',': '*a*q4',
    '.': 'ZFd2P',
    ':': '5@2Pt',
    '?': 'ZT9qH',
    '!': 'z!Pz9',
    'a': 'S+U37',
    'b': 'sR6cM',
    'c': 'BTy45',
    'd': 'P=LG_',
    'e': '%k=H!',
    'f': 'Y92MS',
    'g': '@U!cj',
    'h': '!qgZ5',
    'i': 'pVjTh',
    'j': '%M3pE',
    'k': '=8V6#',
    'l': 'H-+Cn',
    'm': 'naUqw',
    'n': '9*C3$',
    'o': 'hJ@dm',
    'p': '9fvq*',
    'q': 'wTaVP',
    'r': '!4nN6',
    's': 'Mhsdh',
    't': 'p=CM9',
    'u': 'YXHjh',
    'v': 'Gmw8s',
    'w': 'VrSEF',
    'x': '$?!Vj',
    'y': 'm$B9y',
    'z': 'h@+sM',
    'ç': 'C8nnM',
}

encrypting_four_bit = {
    'A': '9bNC_n',
    'B': 'Q2_zxN',
    'C': '7nD!Ks',
    'D': '#W5dve',
    'E': 'F8&?p$',
    'F': '#9!Fze',
    'G': 'F4Um!3',
    'H': '&D3mp=',
    'I': '!g@9Zm',
    'J': 'R5yz$&',
    'K': '3$aYsq',
    'L': '#FR7yj',
    'M': '&tu8N?',
    'N': 'wF9-6b',
    'O': 'e^St52',
    'P': ')eD9LY',
    'Q': 'Em2B_&',
    'R': 'a*Z+75',
    'S': '5Ym^cq',
    'T': 'S+Ns3d',
    'U': '&uVY8t',
    'V': 'T_xA6u',
    'W': '?Dm@7E',
    'X': '5?@QvW',
    'Y': '6sN+G^',
    'Z': 'N$2$y+',
    'Ç': 'fy@3Hc',
    '0': 'rM6_7F',
    '1': '-tPF8?',
    '2': '=5=Sdr',
    '3': 'fr%5Ka',
    '4': 'V6^#eh',
    '5': '64=Qu6',
    '6': 'H!uu5Z',
    '7': '4h-aGH',
    '8': 'B?3@zW',
    '9': 'J4a@Z2',
    ' ': '2JbB*+',
    ',': 'su9R!_',
    '.': 'G?4vZ+',
    ':': 'xYJ^3^',
    '?': 'hW-2Vc',
    '!': '5p?X&K',
    'a': 'a8U_w!',
    'b': 'a8U_w!',
    'c': 'j+S2+p',
    'd': 'x4pE!&',
    'e': 'w5g$Yp',
    'f': 'W?q7zT',
    'g': 'tj?E6n',
    'h': '#8GuHh',
    'i': 'Ng_=2G',
    'j': 'q6L#!F',
    'k': '7+RgDF',
    'l': 'ak=N3q',
    'm': 'X$x9@g',
    'n': 'Zt!6=T',
    'o': '=W2fLZ',
    'p': '54-pH^',
    'q': 'r2pK#D',
    'r': 'S$9Cs7',
    's': '@7YzP4',
    't': 'gY?8L+',
    'u': '#Dm4=t',
    'v': '#4bJ2a',
    'w': 'w8X$A4',
    'x': 'zA-A3=',
    'y': 'N^j6fV',
    'z': 'q3B*kn',
    'ç': 'pX_8gr',
}
