keys = [
    'oi12u809a548gbux',
    '21i3ouain091jamp',
    '9213087210hasda1'
]

encrypting_upper_alphabet = {
    'A': '/Gk,',
    'B': ':.k9',
    'C': '19kç',
    'D': '[})a',
    'E': 'Mba)',
    'F': '/*+l',
    'G': '$3%k',
    'H': '0k1]',
    'I': '36j*',
    'J': 'aZjm',
    'K': 'A@!Ç',
    'L': '#gb0',
    'M': 'ç.HG',
    'N': '84a1',
    'O': '6fA!',
    'P': 'O0lm',
    'Q': '=[.X',
    'R': '58jh',
    'S': '*byc',
    'T': '#kOp',
    'U': 'ÇxZ7',
    'V': 'odKS',
    'W': '0pç,',
    'X': '.;@*',
    'Y': '+=_h',
    'Z': '8Asc',
    'Ç': '7*0a'
}

encrypting_numbers = {
    '0': '=+8b',
    '1': 'Vc8H',
    '2': 'Eo%$',
    '3': '/;.T',
    '4': '*8q>',
    '5': '<{]1',
    '6': '7hj,',
    '7': '09km',
    '8': '8jm&',
    '9': '+.0z',
    ' ': '10m,',
    ',': '21Ja',
    '.': '9*m)',
    ':': '1%4v',
    '?': '9!@6',
    '!': '19,l'
}

encrypting_lower_alphabet = {
    'a': 'O81.',
    'b': ']kP2',
    'c': '!$/k',
    'd': '9*-n',
    'e': '@Mbç',
    'f': 'od#P',
    'g': '7Az|',
    'h': 'q^~u',
    'i': 'çl.,',
    'j': ';?kq',
    'k': '81*+',
    'l': ')pmd',
    'm': '7Dm@',
    'n': '09k,',
    'o': 'ç.;!',
    'p': 'uI8&',
    'q': 'Qe%7',
    'r': '0j,+',
    's': ']{m:',
    't': 'Jxz=',
    'u': '/3m,',
    'v': '1.?0',
    'w': '0,fe',
    'x': 'PqEo',
    'y': '0-_=',
    'z': 'pçW3',
    'ç': '1*#4',
}

what_to_do = {
    1: 'Criptografar um arquivo',
    2: 'Descriptografar um arquivo',
    3: 'Criptografar um texto',
    4: 'Descriptografar um texto'
}

encrypting_one_bit = {
    'A': '&F?2dtfZ87+!^J2+',
    'B': '5#kWw#U!9UtNU3sa',
    'C': 'FhH6DHr&a!WXyEDn',
    'D': 'zm95+^fXegXHg4gH',
    'E': 'yd^75hHWL^5K@kx#',
    'F': 'cdFNMW%WkM5n+JR#',
    'G': '2?uLFs??B3Ec4gkp',
    'H': '6*F!GK8xk5U*VFXm',
    'I': 'atZ5?-$UyHKJsx9$',
    'J': 'M^3!P^m8Yu?eb?RH',
    'K': 'Ve+?Q6xqAuS62+BD',
    'L': 'eFr8=DykYa@tT!9j',
    'M': 'ZAPap$6wc7Z%YWBe',
    'N': 'euc7dZ5L+*Mu6u8p',
    'O': 'WEp^!#4tP&=jK&7B',
    'P': 'VUvPj_dCEnShe847',
    'Q': '5!%zgvs8M5?*buRd',
    'R': 'H@fRw3#H$r@n&m=t',
    'S': 'Udx)u853P^z@Zg$c',
    'T': '$XH-Mfbpx85+7+Q$',
    'U': 'A#5uJSKfxtk@R^R&',
    'V': 'fJc42FuyP*R!87_A',
    'W': 'YX3FM_&8mt45?u8#',
    'X': 'bm=@TYz5$qhR=GB8',
    'Y': 'DN@aGs8B7rDTCPpF',
    'Z': '@xJZx9?4eBeKYZ^U',
    'Ç': 'H7D$KsJtzv+2YjF$',
    '0': '_w@s+2D9Fn_-n287',
    '1': 'd58b-yxEVzx2eV_K',
    '2': '_DwP5-Q9bGwxeT@=',
    '3': '5xN5fX#KG&UcaEyq',
    '4': 'bL@^?s#38ThKKf!C',
    '5': 'GYPT9Azp6Shx=sw=',
    '6': '++T5VsDvb9*!FYYh',
    '7': 'BAT3eA+RV2md?S+7',
    '8': 'EPWMkqg5FpA3^yVU',
    '9': '3Z#^4rHBWg@YU_3D',
    ' ': 'HGsWZktYrwde4=&=',
    ',': 'J*a*Rqu4vs_M2S&A',
    '.': 'UZFdy2fPG*%v97vV',
    ':': '#5@2HPTtBUMV2tJ@',
    '?': 'VZT9Fq8H?!pMxh&U',
    '!': 'Kz!PtzR9#?zDzheX',
    'a': 'kS+U&397#yE8ugz@',
    'b': '6sR6*cqMSk&_3gTd',
    'c': '&BTy=4J5dy!NMVbr',
    'd': 'qP=LvGh_=p6Lwf5r',
    'e': 'X%k=^H=!5rD_@*bD',
    'f': 'rY92hMFSXsZK+5H*',
    'g': 'j@U!*c?js#wD2yLP',
    'h': '#!qgnZE5J*gGz36x',
    'i': '=pVjNTGhq_+828_b',
    'j': 'J%M35pAE+zR#KwHn',
    'k': '9=8Vv65#rgPQs!9B',
    'l': 'UH-+4CrnhLgz_ZYC',
    'm': '4naU%qnwRqUzg2R8',
    'n': 'P9*C_3n$dAfYkNJ7',
    'o': 'RhJ@AdNmLK!Qe8-r',
    'p': 'd9fv^qB*TWM6#_Cv',
    'q': 'wwTa3VPPdgNp%?3v',
    'r': 'B!4nGNY6U6K3KMeN',
    's': 'UMhs8dchYq%Y*-Dd',
    't': 'Yp=CrMB9L=j=*j6k',
    'u': 'rYXH^jch49uks&?w',
    'v': '!GmwB8CszE#TeGHN',
    'w': 'aVrSrEJF?J6RBtch',
    'x': 'p$?!eV8j8?cGu6xt',
    'y': 'Rm$Bf9Gyu6ATY$Y6',
    'z': 'yh@+Us2MQr8H!P5k',
    'ç': 'bC8n*ndMA#saU5=p',
}
